# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dab6c74128f233f184169b7630895d708d78afeac86f7976b076079e149dfb2af6a77910b3ac7acf926b7870e8c8f2b9e13c85ab4823209f45f81621d18a85f1

test:
  secret_key_base: 26a87e3b696271351f62de2bdf24422f648f1c2eb1c0e2429af8d6a697058012c7249c26620be19504477d895951508087f9cd259d136abbe8cf6595987fd6bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
